In [110]:
import pandas as pd
data = pd.read_csv('anc dataset.csv')
data.head()

,Age,Abortion,Baby_wieght,Pre_eclampsia,Multiple_Px,Vaginal_bleeding,BP_greaterthan_90,DM,Renal_disease,Cardiac_disease,Chronic_disease,Presentation,Urine_test_for_protein,Hemoglobin,Rh_status,Complication
0,20,0,0,0,0,0,0,0,0,0,0,1,0,13.1,1,1
1,21,0,0,0,0,1,0,0,0,0,0,1,0,14.8,1,1
2,22,0,1,0,0,0,0,0,0,0,0,1,0,12.9,1,1
3,23,0,1,0,0,0,0,0,0,0,0,1,0,13.9,1,1
4,23,0,1,0,0,0,0,0,0,0,0,1,0,11.0,1,1

In [111]:
data.shape

(2000, 16)

In [112]:
data.Complication.value_counts()

0    1680
1     320
Name: Complication, dtype: int64

In [113]:
X = data.iloc[:,:-1]
y = data.Complication
X.head()

,Age,Abortion,Baby_wieght,Pre_eclampsia,Multiple_Px,Vaginal_bleeding,BP_greaterthan_90,DM,Renal_disease,Cardiac_disease,Chronic_disease,Presentation,Urine_test_for_protein,Hemoglobin,Rh_status
0,20,0,0,0,0,0,0,0,0,0,0,1,0,13.1,1
1,21,0,0,0,0,1,0,0,0,0,0,1,0,14.8,1
2,22,0,1,0,0,0,0,0,0,0,0,1,0,12.9,1
3,23,0,1,0,0,0,0,0,0,0,0,1,0,13.9,1
4,23,0,1,0,0,0,0,0,0,0,0,1,0,11.0,1

In [114]:
# Stratification based train-test dataset spliting

from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=10, stratify=y)

In [115]:
#from sklearn.ensemble import RandomForestClassifier
#model = RandomForestClassifier()

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', max_iter=1000)

model.fit(X_train,y_train)
y_predict = model.predict(X_test)

In [116]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
print("accuracy: {}".format(accuracy_score(y_test, y_predict)))
print("confusion: {}".format(confusion_matrix(y_test, y_predict)))
pd.crosstab(y_test,y_predict)

accuracy: 0.85
confusion: [[496   8]
 [ 82  14]]

col_0           0   1
Complication
0             496   8
1              82  14

In [117]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()

In [118]:
X_train_smote, y_train_smote = smote.fit_sample(X_train,y_train)

In [119]:
from collections import Counter
print("Before SMOTE :" , Counter(y_train))
print("After SMOTE :" , Counter(y_train_smote))

Before SMOTE : Counter({0: 1176, 1: 224})
After SMOTE : Counter({0: 1176, 1: 1176})

In [126]:
model.fit(X_train_smote,y_train_smote)
y_predict = model.predict(X_test)

print(accuracy_score(y_test,y_predict))
print(confusion_matrix(y_test, y_predict))
pd.crosstab(y_test,y_predict)

0.6716666666666666
[[342 162]
 [ 35  61]]

col_0           0    1
Complication
0             342  162
1              35   61